version: "3.8"
services:
  postgresdb:
    container_name: postgresdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgresdb_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=AbcUser1234*
      - POSTGRES_DB=anonfiles
  upload.api:
    container_name: upload.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://identityserver.api
      - "ConnectionStrings:DefaultConnection=User ID=sa; Password=AbcUser1234*; Server=postgresdb; Port=5432;Database=anonfiles;Integrated Security=true;Pooling=true"
    ports:
      - "5002:80"
    depends_on:
      - postgresdb
  identityserver.api:
    container_name: identityserver.api
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=User ID=sa; Password=AbcUser1234*; Server=postgresdb; Port=5432;Database=anonfiles;Integrated Security=true;Pooling=true"
    ports:
      - "5001:80"
    depends_on:
      - postgresdb
  aspnetcoremvc.web:
    container_name: aspnetcoremvc.web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ServiceApiSettings:IdentityBaseUri=http://identityserver.api
      - ServiceApiSettings:ApiBaseUri=http://upload.api

    ports:
      - "5003:80"
   
      