version: '3.8'
services:
  postgresdb:
    image: postgres
  minio: 
    image: minio/minio
  upload.api:
    image: upload_api_image
    build:
      context: /src/services/Api/
      dockerfile: Presentation/FileUpload.Api/Dockerfile
  identityserver.api:
    image: identityserver_api_image
    build:
      context: /src/services/Api/
      dockerfile: Presentation/FileUpload.Identity.Server/Dockerfile
  aspnetcoremvc.web:
    image: aspnetcoremvc.web_image
    build:
      context: /src/Clients/MVCClient/
      dockerfile: Presentation/FileUpload.MVC/Dockerfile

volumes:
  postgresdb_volume:
  minio_volume:
